import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BookOpenCheck, FileText, Scale, ShieldCheck } from "lucide-react";

export default function GuidancePage() {
  return <main className="guidance-page"><header className="schedule-header"><Link href="/" className="schedule-brand"><span className="brand-mark"><BookOpenCheck size={19}/></span><span>ENADE CC<small>ORIENTAÇÕES E REFERÊNCIAS</small></span></Link><Link href="/" className="schedule-back"><ArrowLeft size={15}/> Voltar ao painel</Link></header><div className="guidance-layout">
    <p className="eyebrow">BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO</p><h1>Como usar este laboratório</h1><p className="guidance-lead">Prepare-se com a prova pública de 2021 como referência de estilo e consulte as normas específicas da edição vigente antes de estudar prazos e conteúdos.</p>
    <div className="guidance-callout"><Scale size={20}/><div><strong>O conteúdo não é definido por um único decreto anual.</strong><p>A Lei nº 10.861/2004 instituiu o SINAES e prevê o Enade. Para cada edição, o Inep publica editais, portarias e diretrizes de prova. Em 2026, confira a Portaria Inep nº 157, de 14 de abril, para o componente específico de Bacharelado em Ciência da Computação, e o Edital nº 61, de 14 de maio, para procedimentos e prazos dos bacharelados. A Portaria MEC nº 276/2026 dispõe sobre o Enade da edição.</p></div></div>
    <section className="guidance-section"><div className="guidance-heading"><span><FileText size={18}/></span><div><p className="eyebrow">NORMAS E PROVA</p><h2>Fontes oficiais para conferir</h2></div></div><div className="source-list">
      <a href="https://www.gov.br/inep/pt-br/centrais-de-conteudo/legislacao/enade/2026" target="_blank" rel="noreferrer"><div><strong>Legislação do Enade 2026</strong><span>Portarias, editais e atualizações da edição.</span></div><ArrowUpRight size={16}/></a>
      <a href="https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enade/provas-e-gabaritos/2021" target="_blank" rel="noreferrer"><div><strong>Provas e gabaritos do Enade 2021</strong><span>Consulte o caderno do Bacharelado em Ciência da Computação e seus materiais oficiais.</span></div><ArrowUpRight size={16}/></a>
      <a href="https://www.gov.br/inep/pt-br/acesso-a-informacao/perguntas-frequentes/exame-nacional-de-desempenho-dos-estudantes-enade" target="_blank" rel="noreferrer"><div><strong>Perguntas frequentes do Inep</strong><span>Informações sobre o exame, legislação, cronograma e participação.</span></div><ArrowUpRight size={16}/></a>
      <a href="https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l10.861.htm" target="_blank" rel="noreferrer"><div><strong>Lei nº 10.861/2004 — SINAES</strong><span>Base legal do Sistema Nacional de Avaliação da Educação Superior.</span></div><ArrowUpRight size={16}/></a>
      <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/decreto/d9235.htm" target="_blank" rel="noreferrer"><div><strong>Decreto nº 9.235/2017</strong><span>Regulação, supervisão e avaliação de instituições e cursos superiores no sistema federal.</span></div><ArrowUpRight size={16}/></a>
    </div></section>
    <section className="guidance-section"><div className="guidance-heading"><span><ShieldCheck size={18}/></span><div><p className="eyebrow">INCLUSÃO E ACESSIBILIDADE</p><h2>Acesso como parte do estudo</h2></div></div><p className="guidance-body">A plataforma foi planejada com navegação por teclado, foco visível, títulos semânticos, formulários rotulados, mensagens de estado, contraste revisado, adaptação a telas pequenas e preferência por movimento reduzido. São práticas de desenvolvimento alinhadas às WCAG 2.2 do W3C. No Brasil, a Lei Brasileira de Inclusão (Lei nº 13.146/2015) estabelece obrigações de acessibilidade na educação e em sítios na internet, nos termos da legislação.</p><div className="source-chips"><a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13146.htm" target="_blank" rel="noreferrer">Lei Brasileira de Inclusão <ArrowUpRight size={14}/></a><a href="https://www.w3.org/TR/WCAG22/" target="_blank" rel="noreferrer">W3C WCAG 2.2 <ArrowUpRight size={14}/></a></div></section>
    <section className="guidance-section"><div className="guidance-heading"><span><BookOpenCheck size={18}/></span><div><p className="eyebrow">ESTRATÉGIA DE REVISÃO</p><h2>Faça o estudo render</h2></div></div><ol className="study-tips"><li><strong>Comece pelo diagnóstico.</strong> Faça um simulado e observe temas e raciocínios que exigem revisão.</li><li><strong>Alterne fundamentos e aplicação.</strong> Relacione conceitos de computação a casos, dados e impactos sociais.</li><li><strong>Revise com feedback.</strong> Leia os comentários, registre dúvidas e retorne aos tópicos de menor desempenho.</li><li><strong>Confira prazos oficiais.</strong> O painel organiza datas, mas retificações devem ser verificadas nas páginas do Inep e no Sistema Enade.</li></ol></section>
    <div className="guidance-actions"><Link href="/cronograma">Ver cronograma e lembretes <ArrowUpRight size={15}/></Link><Link href="/#simulado">Iniciar simulado <ArrowUpRight size={15}/></Link></div>
  </div></main>;
}

