import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";

export const metadata = {
  title: "Privacidade | ENADE CC",
  description: "Informações sobre cadastro, dados e progresso acadêmico no Laboratório ENADE CC.",
};

export default function PrivacyPage() {
  const controller = process.env.NEXT_PUBLIC_DATA_CONTROLLER || "Responsável pela publicação do Laboratório ENADE CC";
  const contact = process.env.NEXT_PUBLIC_PRIVACY_CONTACT;
  return <main className="schedule-page"><header className="schedule-header"><Link href="/" className="schedule-brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span>ENADE CC<small>PRIVACIDADE</small></span></Link><Link href="/" className="schedule-back"><ArrowLeft size={15}/> Voltar ao painel</Link></header><article className="schedule-layout privacy-page"><p className="eyebrow">DADOS E PROTEÇÃO</p><h1>Privacidade e uso de dados</h1><p className="privacy-updated">Versão inicial para revisão pelo responsável antes de abrir o cadastro ao público.</p><h2>Quem administra o serviço</h2><p>{controller}. {contact ? <>Contato sobre privacidade: <a href={`mailto:${contact}`}>{contact}</a>.</> : <strong>O administrador precisa configurar e publicar um canal de contato para solicitações de privacidade antes de receber cadastros.</strong>}</p><h2>O que funciona sem cadastro</h2><p>O visitante pode acessar orientações, cronograma, questões e concluir simulados sem criar conta. Nesse modo, as respostas não são associadas a um perfil nem sincronizadas entre dispositivos.</p><h2>Dados usados ao criar uma conta</h2><p>O cadastro por e-mail usa o serviço de autenticação Supabase. O Laboratório guarda o nome de exibição, etapa do curso, endereço público de GitHub se informado, tentativas de simulado e progresso por área. A senha é processada pelo serviço de autenticação e não é armazenada pelo código do Laboratório.</p><h2>Finalidade e acesso</h2><p>Esses dados servem para manter o perfil e exibir ao próprio aluno seu histórico e lembretes de revisão. As políticas de acesso do banco limitam cada perfil e progresso à conta autenticada correspondente. O vínculo com GitHub é opcional e apenas abre o perfil público informado; o site não acessa repositórios nem pede tokens.</p><h2>Serviços de hospedagem</h2><p>Na configuração prevista, o aplicativo é hospedado na Vercel e a autenticação e o banco de dados ficam no Supabase. Consulte os avisos e termos desses fornecedores para conhecer o tratamento realizado por eles. O responsável pela publicação deve informar a região do banco e os prazos de retenção aplicáveis ao projeto.</p><h2>Consulta, correção e exclusão</h2><p>Para solicitar acesso, correção ou exclusão, use o canal de contato publicado acima. A exclusão da conta remove também o perfil, os simulados e o progresso vinculados, conforme a política de retenção definida pelo responsável.</p><h2>Antes de publicar para alunos</h2><p>O administrador deve identificar a instituição ou pessoa responsável, configurar contato de privacidade, definir retenção e exclusão, revisar as regras do Supabase e validar os avisos institucionais aplicáveis. Esta página é um rascunho informativo do funcionamento técnico; não substitui a revisão jurídica e institucional.</p><footer className="privacy-footer"><Link href="/">Voltar ao início</Link><Link href="/orientacoes">Orientações do ENADE</Link></footer></article></main>;
}
